# Generated by Django 5.0.3 on 2024-03-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorite_albums",
            field=models.TextField(blank=True, help_text="Other favorite albums"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_artists",
            field=models.TextField(
                blank=True, help_text="Other bands or singers they like"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="genre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instruments",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recent_albums",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="record_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_media_reach",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="upcoming_events",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="years_active",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
