# Generated by Django 5.0.3 on 2024-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0002_userprofile_favorite_albums_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="instagram_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="spotify_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="twitter_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
