# Generated by Django 5.0.3 on 2024-03-28 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0003_userprofile_instagram_link_userprofile_spotify_link_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BandProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("social_media_reach", models.IntegerField(default=0)),
                ("instagram_link", models.URLField(blank=True, null=True)),
                ("spotify_link", models.URLField(blank=True, null=True)),
                ("twitter_link", models.URLField(blank=True, null=True)),
                ("upcoming_events", models.TextField(blank=True)),
                ("recent_albums", models.TextField(blank=True)),
                (
                    "favorite_artists",
                    models.TextField(
                        blank=True, help_text="Other bands or singers they like"
                    ),
                ),
                (
                    "favorite_albums",
                    models.TextField(blank=True, help_text="Other favorite albums"),
                ),
                ("website", models.URLField(blank=True)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("record_label", models.CharField(blank=True, max_length=100)),
                ("years_active", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndividualProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("social_media_reach", models.IntegerField(default=0)),
                ("instagram_link", models.URLField(blank=True, null=True)),
                ("spotify_link", models.URLField(blank=True, null=True)),
                ("twitter_link", models.URLField(blank=True, null=True)),
                ("upcoming_events", models.TextField(blank=True)),
                ("recent_albums", models.TextField(blank=True)),
                (
                    "favorite_artists",
                    models.TextField(
                        blank=True, help_text="Other bands or singers they like"
                    ),
                ),
                (
                    "favorite_albums",
                    models.TextField(blank=True, help_text="Other favorite albums"),
                ),
                ("instruments", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
