# Generated by Django 5.0.3 on 2024-03-28 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0004_bandprofile_individualprofile_delete_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bandprofile",
            name="social_media_reach",
        ),
        migrations.RemoveField(
            model_name="individualprofile",
            name="social_media_reach",
        ),
    ]
