# Generated by Django 5.0.3 on 2024-03-28 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0005_remove_bandprofile_social_media_reach_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bandprofile",
            name="record_label",
        ),
    ]
