# Generated by Django 5.0.3 on 2024-04-06 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0006_remove_bandprofile_record_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualprofile",
            name="user",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("instagram_link", models.URLField(blank=True, null=True)),
                ("spotify_link", models.URLField(blank=True, null=True)),
                ("twitter_link", models.URLField(blank=True, null=True)),
                ("upcoming_events", models.TextField(blank=True)),
                (
                    "favorite_artists",
                    models.TextField(
                        blank=True, help_text="Other bands or singers they like"
                    ),
                ),
                (
                    "favorite_albums",
                    models.TextField(blank=True, help_text="Other favorite albums"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BandProfile",
        ),
        migrations.DeleteModel(
            name="IndividualProfile",
        ),
    ]
