# Generated by Django 5.0.3 on 2024-04-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0007_remove_individualprofile_user_userprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_photo", models.ImageField(upload_to="artist_photos")),
                ("artist_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
    ]
