# Generated by Django 5.0.3 on 2024-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0008_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_photo", models.URLField()),
                ("artist_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Events",
        ),
    ]
