# Generated by Django 5.0.3 on 2024-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0009_event_delete_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="upcoming_events",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="upcoming_events",
            field=models.ManyToManyField(blank=True, to="wisapp.event"),
        ),
    ]
