# Generated by Django 5.0.3 on 2024-04-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0010_remove_userprofile_upcoming_events_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("photo", models.URLField()),
                ("genre", models.CharField(max_length=50)),
                ("bio", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="artist_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="artist_photo",
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="wisapp.artist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="wisapp.artist",
            ),
        ),
    ]
