# Generated by Django 5.0.3 on 2024-04-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0012_album_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="spotify_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
