# Generated by Django 5.0.3 on 2024-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0013_artist_spotify_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="favorite_artists",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_artists",
            field=models.ManyToManyField(
                related_name="favorited_by", to="wisapp.artist"
            ),
        ),
    ]
