# Generated by Django 5.0.3 on 2024-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0014_remove_userprofile_favorite_artists_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
