# Generated by Django 5.0.3 on 2024-04-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0015_event_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='photo',
            new_name='artist_photo',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='artist',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='photo',
            new_name='event_photo',
        ),
    ]
