# Generated by Django 5.0.3 on 2024-04-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0016_rename_name_artist_artist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_photo',
            new_name='photo',
        ),
    ]
