# Generated by Django 5.0.3 on 2024-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0018_rename_event_photo_event_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="favorite_albums",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_albums",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="wisapp.album"
            ),
        ),
    ]
