# Generated by Django 5.0.3 on 2024-05-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0021_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
