# Generated by Django 5.0.3 on 2024-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0022_news_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="publication_date",
            field=models.DateTimeField(),
        ),
    ]
