# Generated by Django 5.0.3 on 2024-05-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wisapp", "0023_alter_news_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="publication_date",
            field=models.DateField(),
        ),
    ]
